name: GeyserUpdater
main: org.geyserupdater.spigot.SpigotGeyserUpdaterPlugin
version: 1.0.0
api-version: 1.19
author: neha
commands:
  geyserupdate:
    description: Geyser/Floodgateの更新チェックを実行します
    usage: /geyserupdate
    permission: geyserupdater.admin
permissions:
  geyserupdater.admin:
    description: GeyserUpdaterの管理コマンドを実行できます
    default: op
